name       : mccabe
version    : 0.6.1
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/m/mccabe/mccabe-0.6.1.tar.gz : dd8d182285a0fe56bace7f45b5e7d1a6ebcbf524e8f3bd87eb0f125271b8831f
homepage   : https://github.com/pycqa/mccabe
license    : MIT
component  : programming.python
summary    : McCabe checker, plugin for flake8
description: |
    This module provides a plugin for flake8, the Python code checker.
builddeps  :
    - pytest-runner
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
