name       : mccabe
version    : 0.6.1
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/m/mccabe/mccabe-0.6.1.tar.gz : dd8d182285a0fe56bace7f45b5e7d1a6ebcbf524e8f3bd87eb0f125271b8831f
license    : MIT
component  : programming.python
summary    : McCabe checker, plugin for flake8
description: |
    McCabe checker, plugin for flake8
builddeps  :
    - pytest-runner
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
