name       : mccabe
version    : 0.6.1
release    : 3
source     :
    - https://pypi.python.org/packages/06/18/fa675aa501e11d6d6ca0ae73a101b2f3571a565e0f7d38e062eec18a91ee/mccabe-0.6.1.tar.gz : dd8d182285a0fe56bace7f45b5e7d1a6ebcbf524e8f3bd87eb0f125271b8831f
license    : MIT
component  : programming.python
summary    : McCabe checker, plugin for flake8
description: |
    McCabe checker, plugin for flake8
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - pytest-runner
    - python-pytest
    - py
rundeps    :
    - py
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
